server:
  #port: 7020
  port: 8090
management:
  #port: 9218
  port: 8091
  context-path: '/e58a0ff5-9f60-4545-9aa2-2b91c8a6d53b'
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: 'http://discovery1:8761/eureka/'
    registry-fetch-interval-seconds: 5
  instance:
    metadata-map:
      cluster: prontera
      management:
        port: ${management.port}
        context-path: ${management.context-path}
      health:
        path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    prefer-ip-address: true
    ip-address: discovery1
    lease-renewal-interval-in-seconds: 10
spring:
  application:
    name: 'spring-boot-admin'
  cloud:
    loadbalancer:
      retry:
        enabled: true
security:
  basic:
    enabled: false
endpoints:
  actuator:
    enabled: false
    sensitive: false
  health:
    sensitive: false
    enabled: false

  #boot:
    #admin:
      #turbine:
        #url: 'http://hystrix_dashboard:8193/turbine.stream'
        #clusters: 'prontera'
